Better remote Gitlab support for git-{fetchpr,applypr}
Allow to specify the type of forge you are working with: gitlab or
github. If not specified, look at the url to figure it out.

Then add support for Gitlab's MR.

Signed-off-by: Lucas De Marchi <lucas.de.marchi@gmail.com>

diff --git a/git-fetchpr b/git-fetchpr
--- a/git-fetchpr
+++ b/git-fetchpr
@@ -5,23 +5,26 @@ set -e
 
 usage() {
     echo "
-Usage: $(basename $0) [OPTIONS] <PR>
-Fetch a pull-request from github
+Usage: $(basename $0) [OPTIONS] <PR/MR>
+Fetch a pull-request from github/gitlab
 
 OPTIONS
-    -b <branch>    Branch on which to checkout this pr
-    -r <remote>    Use <remote>, otherwise uses fetchpr.remote from config
+    -b <branch>   	Branch on which to checkout this pr
+    -r <remote>    	Use <remote>, otherwise uses fetchpr.remote from config
+    -t <github|gitlab>	Force the forge type - default will figure out from url
 " 1>&$1;
     exit $(($1 - 1));
 }
 
 OPT_BRANCH=
 OPT_REMOTE=
+OPT_REMOTE_TYPE=
 args=0
-while getopts "b:r:h" o; do
+while getopts "b:r:t:h" o; do
     case "${o}" in
         b) OPT_BRANCH=${OPTARG}; args=$[$args + 2] ;;
         r) OPT_REMOTE=${OPTARG}; args=$[$args + 2] ;;
+        t) OPT_REMOTE_TYPE=${OPTARG}; args=$[$args + 2] ;;
         h) usage 1;;
         \?) usage 2;;
     esac
@@ -32,7 +35,19 @@ find_remote() {
 	if [[ -n "$OPT_REMOTE" ]]; then
 		return
 	fi
-	OPT_REMOTE="$(git config --get fetchpr.remote)"
+
+	OPT_REMOTE="$(git config --get fetchpr.remote || true)"
+
+	if [[ -z "$OPT_REMOTE" ]]; then
+		remotes=($(git remote))
+		if [[ ${#remotes[@]} -eq 1 ]]; then
+			OPT_REMOTE=${remotes[0]}
+		elif [[ "${remotes[*]}" == *"origin "* ]]; then
+			OPT_REMOTE=origin
+		fi
+
+		echo "Remote auto-detect:  $OPT_REMOTE"
+	fi
 }
 
 find_remote
@@ -43,4 +58,19 @@ if [[ -n "$OPT_BRANCH" ]] && git rev-parse --verify -q "$OPT_BRANCH"; then
     exit 1
 fi
 
-git fetch $OPT_REMOTE refs/pull/$pr/head:$OPT_BRANCH
+if [[ -z "$OPT_REMOTE_TYPE" ]]; then
+	remote_url=$(git config remote.$OPT_REMOTE.url)
+else
+	remote_url="$OPT_REMOTE_TYPE"
+fi
+
+if [[ "$remote_url" == *github* ]]; then
+	ref=refs/pull/$pr/head
+elif [[ "$remote_url" == *gitlab* ]]; then
+	ref=refs/merge-requests/$pr/head
+else
+	echo "ERROR: Unkonwn remote type - compatible with github/gitlab only"
+	exit 1
+fi
+
+git fetch $OPT_REMOTE $ref:$OPT_BRANCH
