mkosi-resize: rework and fix partition table recreation
This fixes the partition table so you can dd it to a device bigger than
the original image and have the partitions correctly sized afterwards.

diff --git a/mkosi-resize b/mkosi-resize
--- a/mkosi-resize
+++ b/mkosi-resize
@@ -3,12 +3,48 @@
 # run this script on the target disk after dd'ing the image there
 # it only works when the root partition is the last one
 
+set -e
+
 disk=$1
-ROOT_PARTITION_X86_64="4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709"
+ROOT_PARTITION_X86_64="F68BCE3-E8CD-4DB1-96E7-FBCAF984B709"
 
-sfdisk --dump $disk | sed "/$ROOT_PARTITION_X86_64/s/[[:space:]]*size=[[:space:]]*[^,]*,//" | \
-    sfdisk $disk
+# Make sure we print an error message, loud and clear
+trap '
+    ret=$?
+    set +e
+    if [ $ret -ne 0 ]; then
+        echo "Failed to expand root" > /dev/stderr
+    fi
+    ' EXIT
+trap 'exit 1;' SIGINT
 
-read part xxxxx <<<$(sfdisk --dump $disk | grep $ROOT_PARTITION_X86_64)
-e2fsck -f $part
-resize2fs $part
+# Recreate partition table by removing the "last-lba" setting and the root
+# partition size argument. This allows us to later extend the filesystem
+# using the free space and also allows us to put the alternate GPT table to
+# end of the device, where it belongs
+function recreate_partition_table() {
+    ptable=$(mktemp --tmpdir expand-root.XXXXXX)
+
+    # save current GPT description
+    sfdisk --dump $disk | \
+        sed -e "/$ROOT_PARTITION_X86_64/s/[[:space:]]*size=[[:space:]]*[^,]*,//" \
+            -e "/^last-lba/d" > $ptable
+
+    # Erase any partition table, including MBR that might contain old partitions
+    wipefs --all $disk
+
+    # write back partition table
+    sfdisk $disk < $ptable
+
+    rm -f $ptable
+}
+
+function expand_root() {
+    # now figure out what is the root parition and extend it
+    read part xxxxx <<<$(sfdisk --dump $disk | grep $ROOT_PARTITION_X86_64)
+    e2fsck -f $part
+    resize2fs $part
+}
+
+recreate_partition_table
+expand_root
